background_alpha:
  poor: 0.1
  fine: 0.3
  good: 0.4
  excellent: 0.4

logging:
  gdr: "info"

# pas pour le calcul des moyennes
# si on ne précise rien, la valeur est 200
mean_step:

# le nom d'un sous-répertoire de datas
# pour réduire la liste des fichiers affichés
# si on ne précise rien, la valeur est datas
# si on précise sub1/sub2, la valeur est datas/sub1/sub2 
datas:

# Emplacement du fichier xls des états aigle dans datas
aigle_xls : "Aigle3D/Table_Indicateurs_Etat_surface_DIRMC.xlsx"

# emplacement d'un fichier contenant des données en PR+abcisse dans datas
pr_abs_csv: "PR_ABS/exp_N0122_Vauclair.csv"

# affichage des légendes
# si on précise rien, les légendes sont affichées
# si on met true ou 1, c'est pareil
# si on met false ou 0, les légendes ne sont pas affichées
legend:
